# Pivot table

In [1]:
import pandas as pd 
import numpy as np

**PIVOT TABLE**

In [3]:
data ={
    "Date":pd.date_range("2026-01-01",periods=20),
    "Product":["A","B","C","D"] * 5,
    "Region":["East","West","North","South","East","West","North","South","East","West","North","South",
              "East","West","North","South","East","West","North","South"],
    "Sales":np.random.randint(100,200,20),
    "Units":np.random.randint(10,100,20),
    "Rep":["John","Mary","Bob","Alice","John","Mary","Bob","Alice","John","Mary","Bob","Alice","John","Mary","Bob","Alice",
           "John","Mary","Bob","Alice"]
}

df=pd.DataFrame(data)

df["Month"]=df["Date"].dt.month_name()
df["Quarter"]="Q" + df["Date"].dt.quarter.astype(str)

In [4]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2026-01-01       A   East    197     75   John  January      Q1
1  2026-01-02       B   West    144     11   Mary  January      Q1
2  2026-01-03       C  North    187     90    Bob  January      Q1
3  2026-01-04       D  South    131     27  Alice  January      Q1
4  2026-01-05       A   East    127     98   John  January      Q1
5  2026-01-06       B   West    124     42   Mary  January      Q1
6  2026-01-07       C  North    195     84    Bob  January      Q1
7  2026-01-08       D  South    144     71  Alice  January      Q1
8  2026-01-09       A   East    197     67   John  January      Q1
9  2026-01-10       B   West    109     34   Mary  January      Q1
10 2026-01-11       C  North    153     53    Bob  January      Q1
11 2026-01-12       D  South    123     33  Alice  January      Q1
12 2026-01-13       A   East    193     44   John  January      Q1
13 2026-01-14       B   West    149     53   Mary  January      Q1
14 2026-01-15       C  North    136     19    Bob  January      Q1
15 2026-01-16       D  South    176     61  Alice  January      Q1
16 2026-01-17       A   East    166     59   John  January      Q1
17 2026-01-18       B   West    125     63   Mary  January      Q1
18 2026-01-19       C  North    161     28    Bob  January      Q1
19 2026-01-20       D  South    112     95  Alice  January      Q1

In [8]:
pd.pivot_table(df,values="Sales",index="Region",columns="Product",aggfunc="median")

Product      A      B      C      D
Region
East     193.0    NaN    NaN    NaN
North      NaN    NaN  161.0    NaN
South      NaN    NaN    NaN  131.0
West       NaN  125.0    NaN    NaN

In [10]:
table2=pd.pivot_table(df,values=["Sales","Units"],index="Region",columns="Product")
table2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     176.0    NaN    NaN    NaN  68.6   NaN   NaN   NaN
North      NaN    NaN  166.4    NaN   NaN   NaN  54.8   NaN
South      NaN    NaN    NaN  137.2   NaN   NaN   NaN  57.4
West       NaN  130.2    NaN    NaN   NaN  40.6   NaN   NaN

**CROSS TAB**

In [11]:
pd.crosstab(df['Region'],df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0